# Generated by Django 2.2.7 on 2019-11-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=20, verbose_name='Категория')),
                ('product_name', models.CharField(max_length=20, verbose_name='Название')),
                ('product_detail', models.CharField(max_length=200, verbose_name='Описание')),
                ('product_price', models.FloatField(verbose_name='Цена')),
                ('product_amount', models.SmallIntegerField(verbose_name='Количество')),
            ],
        ),
    ]
