# Generated by Django 2.2.7 on 2019-11-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191120_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
